
collision_monitor:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_nav" 
    # cmd_vel_smoothed
    cmd_vel_out_topic: "cmd_vel"
    transform_tolerance: 0.5
    source_timeout: 5.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop" and "slowdown" action types,
    # and robot footprint for "approach" action type.
    # Footprint could be "polygon" type with dynamically set footprint from footprint_topic
    # or "circle" type with static footprint set by radius. "footprint_topic" parameter
    # to be ignored in circular case.
    polygons: ["PolygonStop", "PolygonSlow"]
    PolygonStop:
      type: "polygon"
      points: [0.25, 0.2, 0.25, -0.2, 0.0, -0.2, 0.0, 0.2]
      action_type: "stop"
      max_points: 3
      visualize: True
      polygon_pub_topic: "polygon_stop"
    PolygonSlow:
      type: "polygon"
      points: [0.5, 0.35, 0.5, -0.35, 0.0, -0.35, 0.0, 0.35]
      action_type: "slowdown"
      max_points: 3
      slowdown_ratio: 0.5
      visualize: True
      polygon_pub_topic: "polygon_slowdown"
    # FootprintApproach:
    #   type: "polygon"
    #   action_type: "approach"
    #   footprint_topic: "/local_costmap/published_footprint"
    #   time_before_collision: 2.0
    #   simulation_time_step: 0.1
    #   max_points: 5
    #   visualize: False
    # observation_sources: ["range_left", "range_center", "range_right"]
    observation_sources: ["range_center", "range_left", "range_right"]
    scan:
      type: "scan"
      topic: "/scan"
    pointcloud:
      type: "pointcloud"
      topic: "/intel_realsense_r200_depth/points"
      min_height: 0.1
      max_height: 0.5
    range_left:
      type: "range"
      topic: "/range_left"
    range_center:
      type: "range"
      topic: "/range_center"
    range_right:
      type: "range"
      topic: "/range_right"
